[package]
name = "cli"
version = "0.1.0"
authors = ["willem <willemolding@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.15"
reqwest = "0.9.16"
serde_json = "1.0.39"
linefeed = "0.6.0"
